version: '3'

services:
  postgres:
    container_name: event_db
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  api:
    container_name: event_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
